# Generated by Django 6.0.2 on 2026-03-19 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=64)),
                ("query", models.TextField()),
                ("response", models.TextField()),
                ("agent", models.CharField(max_length=50)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Terrible"),
                            (2, "Bad"),
                            (3, "OK"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FineTuneJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("openai_job_id", models.CharField(blank=True, max_length=100)),
                (
                    "base_model",
                    models.CharField(default="gpt-4o-mini-2024-07-18", max_length=100),
                ),
                ("fine_tuned_model", models.CharField(blank=True, max_length=200)),
                ("training_file_id", models.CharField(blank=True, max_length=100)),
                ("num_examples", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LLMSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        help_text="Django session key", max_length=64, unique=True
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("google", "Google Gemini"),
                            ("anthropic", "Anthropic Claude"),
                        ],
                        default="openai",
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(default="gpt-4o-mini", max_length=100)),
                ("temperature", models.FloatField(default=0.7)),
                ("top_p", models.FloatField(default=1.0)),
                ("frequency_penalty", models.FloatField(default=0.0)),
                ("presence_penalty", models.FloatField(default=0.0)),
                ("max_tokens", models.IntegerField(default=1024)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM Settings",
                "verbose_name_plural": "LLM Settings",
            },
        ),
        migrations.CreateModel(
            name="ObservabilityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(db_index=True, default="", max_length=64),
                ),
                ("session_key", models.CharField(blank=True, max_length=64)),
                ("agent", models.CharField(max_length=50)),
                (
                    "step",
                    models.CharField(
                        help_text="e.g., route_intent, retrieve, generate",
                        max_length=50,
                    ),
                ),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("tokens_used", models.IntegerField(default=0)),
                ("latency_ms", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ResponseCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("query_text", models.TextField()),
                ("response_text", models.TextField()),
                ("agent", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=100)),
                ("hit_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-hit_count"],
            },
        ),
        migrations.CreateModel(
            name="TokenUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("session_key", models.CharField(blank=True, max_length=64)),
                ("agent", models.CharField(max_length=50)),
                ("provider", models.CharField(default="openai", max_length=20)),
                ("model", models.CharField(max_length=100)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("cost_usd", models.FloatField(default=0.0)),
                (
                    "latency_ms",
                    models.IntegerField(
                        default=0, help_text="Response time in milliseconds"
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("amount", models.IntegerField(help_text="Amount in UGX")),
                (
                    "tax_amount",
                    models.IntegerField(default=0, help_text="VAT in UGX (18%)"),
                ),
                (
                    "total_amount",
                    models.IntegerField(help_text="Total incl tax in UGX"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="bakery.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("mobile_money", "Mobile Money (MTN/Airtel)"),
                            ("stripe", "Stripe (Card)"),
                            ("flutterwave", "Flutterwave"),
                            ("manual", "Manual / Cash"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=200)),
                ("amount", models.IntegerField(help_text="Amount in UGX")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="For Mobile Money", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="bakery.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
