# Generated by Django 6.0.2 on 2026-03-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0002_feedback_finetunejob_llmsettings_observabilitylog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmsettings",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("google", "Google Gemini"),
                    ("anthropic", "Anthropic Claude"),
                    ("grok", "Grok (xAI)"),
                    ("ollama", "Ollama (Local)"),
                ],
                default="openai",
                max_length=20,
            ),
        ),
    ]
